[project]
name = "dnd5-spells"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "charset-normalizer>=3.4.4",
    "humanize>=4.15.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
